# netlify.toml

[build]
  command = "echo 'No build required'"
  publish = "frontend"

# ▼▼▼ REGLA AÑADIDA PARA LA PÁGINA PRINCIPAL ▼▼▼
# Esto le dice a Netlify que cuando alguien visite tu página principal ("/"),
# debe mostrar el contenido de "/login.html".
[[redirects]]
  from = "/"
  to = "/login.html"
  status = 200

# Regla existente para el backend (no la cambies)
[[redirects]]
  from = "/api/*"
  to = "https://biocaretask-backend.onrender.com/:splat"
  status = 200
  force = true